[package]
name = "slime_os"
version = "0.1.0"
edition = "2021"

[dependencies]
buddy_system_allocator = "0.9.0"
riscv = { version = "0.10.1" }
bitflags = "2.0.0-rc.1"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
