[package]
name = "slime_os"
version = "0.1.0"
edition = "2021"

[dependencies]
buddy_system_allocator = "0.8.0" # we do not achieve the memory allocator ourselves
riscv = "0.9.0"
bitflags = "1.3.2"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
